resources:
   - name: sample_java_repo_test
     type: gitRepo
     repoPath: scriptnull/sample_node
     configuration:
        integrationName: github
        branches:
           except: "*test"
           only: "new-gitrepo*"
        tags:
           except: none
           only: none   
        buildOnCommit: true
        buildOnPullRequest: false
        buildOnPullRequestClose: false
        buildOnRelease: true
        buildOnTagPush: false
        buildOnFileCommit: "*test"
        shallowDepth: 2
        gitConfig: 
          - dont_know
          - dont_know_2
     initialVersion:
       sha: master

   - name: sample_java_file_test
     type: file
     fileUrl: text.js
     configuration:
        integrationName: docker-int
     initialVersion:
       fileName: test
       fileDtTm: test

   - name: sample_java_image_test
     type: image
     imageName: "library/nginx"
     configuration:
       integrationName: docker-int
     initialVersion:
       imageTag: latest

   - name: sample_java_webhook_test
     type: webhook
     configuration:
       integrationName: github
     initialVersion:
       payload: test_payload

   - name: sample_java_kube_test
     type: cluster
     configuration:
       integrationName: kubeIntegration
       bastionHostIP: 1.2.3.4
       bastionUser: sshUser
       bastionIntegrationName: sshKey-int
       
pipelines:
  - name: test_pipeline_1
    setup:
      environmentVariables:
        normal:
          - ENV1: value-pipe-1
          - ENV2: value-pipe-2
        encrypted:
          - SECURE_ENV1: test_value-pipe-1
          - SECURE_ENV2: test_value-pipe-2
      runtime: onHost-pipe
    steps:
      - name: in_trigger_step
        type: runSh
        configuration:
          affinityGroup: test_group 
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
            encrypted:
              - SECURE_ENV1: test_value
              - SECURE_ENV2: test_value
          runtime: onHost
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"

      - name: main_step
        type: runSh
        configuration:
          affinityGroup: test_group 
          priority: 9999
          timeoutSeconds: 40
          cache: true
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
            encrypted:
              - SECURE_ENV1: test_value
              - SECURE_ENV2: test_value
          runtime: onHost
        requires:
          integrations:
            - github
        triggeredBy:
          resources:
            - sample_java_repo_test
          steps:
            - in_trigger_step
        execution:
          onStart:
            - echo "Prepping build environment"
            - echo "on start"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
        outputResources:
          - sample_java_file_test
          - sample_java_webhook_test
